sudo: required
services:
  - docker
before_install:
  - docker pull nimlang/nim
script:
  - docker run nimlang/nim nim --version
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "apt-get update && apt-get install -y libgcrypt20 libgcrypt20-dev && nimble install -dy && nim c -p:. -r tests/test_basic.nim"

